capstone_proj/capstone_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users_app.urls')),
    path('', include('reports_app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

capstone_proj/reports_app/urls.py
from django.urls import path, re_path

from . import views

app_name = 'reports_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('company_lookup/<int:finance_id>', views.company_lookup, name='company_lookup'),
    path('manual_invoice/<int:transaction_number>', views.manual_invoice, name='manual_invoice'),
    path('read_customer/<int:finance_id>', views.read_customer, name="read_customer"),
    path('auth_header/', views.auth_header, name='auth_header'),
    path('sparse_update_customer/', views.sparse_update_customer, name='sparse_update_customer'),
    path('create_new_customer/', views.create_new_customer, name='create_new_customer'),
    path('create_new_invoice/', views.create_new_invoice, name='create_new_invoice'),
    path('email_invoice/<str:invoice_id>/<str:email_address>', views.email_invoice, name='email_invoice'),
    re_path(r'^oauth/?$', views.oauth, name='oauth'),
    re_path(r'^openid/?$', views.openid, name='openid'),
    re_path(r'^callback/?$', views.callback, name='callback'),
    re_path(r'^connected/?$', views.connected, name='connected'),
    re_path(r'^qbo_request/?$', views.qbo_request, name='qbo_request'),
    re_path(r'^revoke/?$', views.revoke, name='revoke'),
    re_path(r'^refresh/?$', views.refresh, name='refresh'),
    re_path(r'^user_info/?$', views.user_info, name='user_info'),
    re_path(r'^migration/?$', views.migration, name='migration'),
    re_path(r'^invoice/?$', views.invoice, name='invoice'),
    re_path(r'^list_customers/?$', views.list_customers, name='list_customers'),
]

capstone_proj/users_app/urls.py
from django.urls import path

from . import views

app_name='users_app'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
]

capstone_proj/templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-secondary">

  <!-- Navbar -->
  <div class="container">
    <!-- Navbar Lgoo -->
    <a class="navbar-brand" href="{% url 'reports_app:index' %}">
      <img src="{% static 'pear_logo.png' %}" alt="Pear Suite Logo" width="200" height="50">
    </a>

    {% if request.user.is_authenticated %}

      <!-- Logout if logged in -->
      <div class="d-flex mx-1">
          <a class="btn btn-outline-light mx-3" href="{% url 'users_app:profile' user.username %}">User Profile</a>
          <a class="btn btn-outline-light mx-3" href="{% url 'users_app:logout' %}">Logout</a>
      </div>

      {% else %}
      <!-- Login for Users/Admin -->
      <div class="btn-group">
        <a class="btn btn-outline-light mx-1" href="{% url 'users_app:login' %}">Login</a>  
        <a class="btn btn-outline-light mx-1" href="{% url 'users_app:register' %}">Sign up</a>
      </div>

    {% endif %}
  
  </div>
</nav>